apiVersion: v1
kind: BuildConfig
metadata:
  name: rh-openshift-bc
  labels:
    app: rh_openshift  
spec:
  output:
    to:
      kind: ImageStreamTag
      name: is_rhos_demo:latest
  resources: {}
  source:
    git:
      ref: master
      uri: https://github.com/arvindvijaya/HelloDevops2.git
    contextDir: ""
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: is_rhos_demo:latest        
    type: Docker
